In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Candy.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [3]:
print(df.shape)
print(df.columns)
df.info()

(10194, 18)
Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

In [4]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df[df['Sales'] <= 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Country/Region, City, State/Province, Postal Code, Division, Region, Product ID, Product Name, Sales, Units, Gross Profit, Cost]
Index: []

In [9]:
df = df[df['Sales'] > 0]

In [8]:
df[df['Cost'] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Country/Region, City, State/Province, Postal Code, Division, Region, Product ID, Product Name, Sales, Units, Gross Profit, Cost]
Index: []

In [10]:
df = df[df['Cost'] >= 0]

In [11]:
df['Units'].isnull().sum()

np.int64(0)

In [12]:
df['Units'] = df['Units'].fillna(df['Units'].median())

In [13]:
df['Product Name'] = df['Product Name'].str.strip()

In [14]:
df['Division'] = df['Division'].str.strip().str.title()

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

In [16]:
df['Gross Margin %'] = (
    df['Gross Profit'] / df['Sales']
) * 100

In [17]:
df['Profit Per Unit'] = (
    df['Gross Profit'] / df['Units']
)

In [18]:
product_summary = df.groupby(
    'Product Name'
).agg({
    'Sales':'sum',
    'Gross Profit':'sum',
    'Cost':'sum',
    'Units':'sum'
}).reset_index()

product_summary

                         Product Name     Sales  Gross Profit     Cost  Units
0              Everlasting Gobstopper    130.00        104.00    26.00     13
1                Fizzy Lifting Drinks     78.75         47.25    31.50     21
2                             Fun Dip     12.00          4.80     7.20      8
3                         Hair Toffee     76.50         59.50    17.00     17
4                           Kazookles   1205.75         92.75  1113.00    371
5                         Laffy Taffy     53.73         33.48    20.25     27
6                  Lickable Wallpaper   7860.00       3930.00  3930.00    393
7                               Nerds     15.00          7.00     8.00     10
8                           SweeTARTS     61.50         28.70    32.80     41
9           Wonka Bar - Fudge Mallows  24890.40      16593.60  8296.80   6914
10         Wonka Bar - Milk Chocolate  26867.75      17443.37  9424.38   8267
11  Wonka Bar - Nutty Crunch Surprise  23574.95      16819.95  6755.00   6755
12  Wonka Bar - Triple Dazzle Caramel  28485.00      18610.20  9874.80   7596
13     Wonka Bar -Scrumdiddlyumptious  27874.80      19357.50  8517.30   7743
14                          Wonka Gum    597.50        310.70   286.80    478

In [35]:
product_summary['Gross Margin %'] = (
    product_summary['Gross Profit']
    / product_summary['Sales']
) * 100
product_summary['Profit Per Unit'] = (
    product_summary['Gross Profit']
    / product_summary['Units']
)
total_sales = product_summary['Sales'].sum()

product_summary['Revenue Contribution %'] = (
    product_summary['Sales']
    / total_sales
) * 100
total_profit = product_summary['Gross Profit'].sum()

product_summary['Profit Contribution %'] = (
    product_summary['Gross Profit']
    / total_profit
) * 100
top_profit_products = product_summary.sort_values(
    by='Gross Profit',
    ascending=False
)

top_profit_products.head(10)

,Product Name,Sales,Gross Profit,Cost,Units,Gross Margin %,Profit Per Unit,Revenue Contribution %,Profit Contribution %
13,Wonka Bar -Scrumdiddlyumptious,27874.80,19357.50,8517.30,7743,69.444444,2.50,19.660098,20.715882
12,Wonka Bar - Triple Dazzle Caramel,28485.00,18610.20,9874.80,7596,65.333333,2.45,20.090472,19.916141
10,Wonka Bar - Milk Chocolate,26867.75,17443.37,9424.38,8267,64.923077,2.11,18.949825,18.667431
11,Wonka Bar - Nutty Crunch Surprise,23574.95,16819.95,6755.00,6755,71.346705,2.49,16.627413,18.000263
9,Wonka Bar - Fudge Mallows,24890.40,16593.60,8296.80,6914,66.666667,2.40,17.555200,17.758030
6,Lickable Wallpaper,7860.00,3930.00,3930.00,393,50.000000,10.00,5.543658,4.205782
14,Wonka Gum,597.50,310.70,286.80,478,52.000000,0.65,0.421417,0.332503
0,Everlasting Gobstopper,130.00,104.00,26.00,13,80.000000,8.00,0.091689,0.111298
4,Kazookles,1205.75,92.75,1113.00,371,7.692308,0.25,0.850416,0.099259
3,Hair Toffee,76.50,59.50,17.00,17,77.777778,3.50,0.053955,0.063675

In [25]:
top_margin_products = product_summary.sort_values(
    by='Gross Margin %',
    ascending=False
)

top_margin_products.head(10)

,Product Name,Sales,Gross Profit,Cost,Units,Gross Margin %,Profit Per Unit,Revenue Contribution %,Profit Contribution %
0,Everlasting Gobstopper,130.00,104.00,26.00,13,80.000000,8.00,0.091689,0.111298
3,Hair Toffee,76.50,59.50,17.00,17,77.777778,3.50,0.053955,0.063675
11,Wonka Bar - Nutty Crunch Surprise,23574.95,16819.95,6755.00,6755,71.346705,2.49,16.627413,18.000263
13,Wonka Bar -Scrumdiddlyumptious,27874.80,19357.50,8517.30,7743,69.444444,2.50,19.660098,20.715882
9,Wonka Bar - Fudge Mallows,24890.40,16593.60,8296.80,6914,66.666667,2.40,17.555200,17.758030
12,Wonka Bar - Triple Dazzle Caramel,28485.00,18610.20,9874.80,7596,65.333333,2.45,20.090472,19.916141
10,Wonka Bar - Milk Chocolate,26867.75,17443.37,9424.38,8267,64.923077,2.11,18.949825,18.667431
5,Laffy Taffy,53.73,33.48,20.25,27,62.311558,1.24,0.037896,0.035829
1,Fizzy Lifting Drinks,78.75,47.25,31.50,21,60.000000,2.25,0.055542,0.050566
14,Wonka Gum,597.50,310.70,286.80,478,52.000000,0.65,0.421417,0.332503

In [26]:
division_summary = df.groupby(
    'Division'
).agg({
    'Sales':'sum',
    'Gross Profit':'sum',
    'Cost':'sum'
}).reset_index()

division_summary

    Division      Sales  Gross Profit      Cost
0  Chocolate  131692.90      88824.62  42868.28
1      Other    9663.25       4333.45   5329.80
2      Sugar     427.48        284.73    142.75

In [27]:
division_summary['Margin %'] = (
    division_summary['Gross Profit']
    / division_summary['Sales']
) * 100

division_summary

    Division      Sales  Gross Profit      Cost   Margin %
0  Chocolate  131692.90      88824.62  42868.28  67.448298
1      Other    9663.25       4333.45   5329.80  44.844643
2      Sugar     427.48        284.73    142.75  66.606625

In [36]:
pareto_df = product_summary.sort_values(
    by='Gross Profit',
    ascending=False
)
pareto_df['Cumulative Profit'] = (
    pareto_df['Gross Profit'].cumsum()
)
pareto_df['Cumulative Profit %'] = (
    pareto_df['Cumulative Profit']
    / total_profit
) * 100
pareto_df[
    pareto_df['Cumulative Profit %'] <= 80
]

,Product Name,Sales,Gross Profit,Cost,Units,Gross Margin %,Profit Per Unit,Revenue Contribution %,Profit Contribution %,Cumulative Profit,Cumulative Profit %
13,Wonka Bar -Scrumdiddlyumptious,27874.80,19357.50,8517.30,7743,69.444444,2.50,19.660098,20.715882,19357.50,20.715882
12,Wonka Bar - Triple Dazzle Caramel,28485.00,18610.20,9874.80,7596,65.333333,2.45,20.090472,19.916141,37967.70,40.632023
10,Wonka Bar - Milk Chocolate,26867.75,17443.37,9424.38,8267,64.923077,2.11,18.949825,18.667431,55411.07,59.299454
11,Wonka Bar - Nutty Crunch Surprise,23574.95,16819.95,6755.00,6755,71.346705,2.49,16.627413,18.000263,72231.02,77.299717

In [39]:
def risk_flag(margin):

    if margin < 20:
        return "High Risk"

    elif margin < 40:
        return "Medium Risk"

    else:
        return "Low Risk"

In [40]:
   product_summary['Risk Flag'] = (
    product_summary['Gross Margin %']
    .apply(risk_flag)
)

In [41]:
df.to_csv(
    "Cleaned_Candy_Data.csv",
    index=False
)

In [42]:
product_summary.to_csv(
    "Product_Profitability.csv",
    index=False
)

In [43]:
division_summary.to_csv(
    "Division_Performance.csv",
    index=False
)